### PR TITLE
feat(core): add selector NBT filters

### LINKED ISSUE #198: feat(core): add selector NBT filters
Parent: #181
Depends on: #221

### Goal

Add repeatable positive and negated vanilla `nbt={...}` selector filters without creating a second SNBT surface.

### Scope

- Add `nbt { ... }` to the common selector scope.
- Negate a structured filter with the uniform prefix form: `!nbt { ... }`.
- Reuse `NbtCompoundScope`, `NbtCompoundBuilder`, and the existing SNBT rendering rules.
- Preserve every positive and negated NBT call in call order.
- Support nested compounds, scalar values, typed arrays, homogeneous lists, key/string escaping, and an empty compound.
- Keep raw SNBT reachable only through the existing `entitySelector("...")` escape hatch.

### API-shape decision

NBT uses the same prefix-negatable filter expression introduced by #221. Kotlin applies `!` to the completed `nbt { ... }` call, so structured and scalar selector filters now share one syntax without a selector-specific negation scope or Boolean flag:

```kotlin
entities {
    nbt { "Health" eq 20.0f }
    !nbt { "Invisible" eq true }
}
```

The selector retains the structured compound until its existing renderer serializes it. No raw-string overload or second SNBT model is introduced.

### Acceptance criteria

- [ ] Positive and negated compounds render as `nbt={...}` and `nbt=!{...}`.
- [ ] Multiple NBT filters are preserved in call order.
- [ ] `nbt { ... }` and `!nbt { ... }` compile on all six typed selector heads.
- [ ] Nested compounds, arrays, lists, escaping, and `{}` use the same output as the existing NBT DSL.
- [ ] Raw SNBT is not accepted by the typed selector DSL.
- [ ] Existing NBT path/component APIs remain unchanged.
- [ ] `EntitySelectorTest` and a selector-component assertion through `SelectorMatchers` cover the feature.
- [ ] Public declarations have explicit visibility, return types, KDoc, and `@sample` coverage.
- [ ] `./gradlew build` is green, including formatting and coverage.

### PR DESCRIPTION
**Pull request by LMLiam**
## Summary

- add repeatable structured `nbt { ... }` filters to every typed selector head
- support negated structured filters with the uniform `!nbt { ... }` syntax from #222
- retain `NbtCompound` values until selector rendering and reuse the canonical SNBT renderer
- reject a raw-string overload while covering nested compounds, arrays, lists, escaping, empty compounds, and selector-component integration

## Design

This PR deliberately adds no selector-specific NBT wrapper or negation scope. NBT participates in the generic repeatable selector-filter model introduced by #222, keeping polarity handling separate from compound construction and serialization.

## Staff review pass (Claude, on top of the original implementation)

- **Rebased onto the merged #222** (its pre-merge base commit is dropped); the renderer wiring now uses the deduplicated `rendered(::renderCompound)` extension from the review pass there.
- **Per-head coverage calls the DSL directly** and asserts the rendered selector (`@p[nbt={},nbt=!{}]` … for all six heads) instead of invoking the embedded compiler — inline test code already proves the calls compile, and the rendering assertion is stronger. The unused `assertCompiles` helper is removed from the test toolkit.
- **The raw-overload compile-fail test pins its diagnostic** ("Argument type mismatch") so it cannot pass on an unrelated compilation error, matching the convention set in #222.

## Validation

- `./gradlew ktlintFormat`
- `./gradlew build` (full: tests, lint, coverage, samples)

Closes #198
Parent: #181

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01WASDpBnBTUbnvDpaNrDFvA

### CODE REVIEW

File: modules/core/src/main/kotlin/io/github/lmliam/kotventure/core/selector/CommonEntitySelectorScope.kt [hunk 1]
```diff
@@ -116,6 +117,15 @@ public sealed interface CommonEntitySelectorScope {
      */
     public fun team(presence: SelectorPresence)
 
+    /**
+     * Adds a structured NBT compound filter.
+     *
+     * Repeated calls preserve every compound in call order.
+     *
+     * @sample io.github.lmliam.kotventure.core.selector.selectorNbtSample
```
Comment (LMLiam) [inline modules/core/src/main/kotlin/io/github/lmliam/kotventure/core/selector/CommonEntitySelectorScope.kt:154]: The deliberate absence of a raw-string overload is an important API constraint in this slice. State it in the public KDoc and point callers with unavoidable raw SNBT to `entitySelector(...)`; otherwise users may reasonably look for or request `nbt(String)` here.

File: modules/core/src/main/kotlin/io/github/lmliam/kotventure/core/selector/SelectorNbtFilter.kt [hunk 2]
```diff
@@ -0,0 +1,9 @@
+package io.github.lmliam.kotventure.core.selector
+
+internal data class SelectorNbtFilter(
+    val compound: String,
```
Comment (LMLiam) [inline modules/core/src/main/kotlin/io/github/lmliam/kotventure/core/selector/SelectorNbtFilter.kt]: `compound` is typed as `String`, but it is specifically canonical rendered SNBT, not an NBT compound model. Rename it to `renderedCompound` so future code does not accidentally treat this as structured data or render it a second time.

File: modules/core/src/test/kotlin/io/github/lmliam/kotventure/core/selector/EntitySelectorTest.kt [hunk 3]
```diff
@@ -455,6 +456,42 @@ class EntitySelectorTest :
...
+                            "Tags" eq list("boss", "hostile")
+                        }
+                        not {
+                            nbt { "Invisible" eq true }
+                        }
+                        nbt {}
+                    }
+
+                selector.asString() shouldBe
+                    "@e[nbt={Health:20.0f,Tags:[\"boss\",\"hostile\"]},nbt=!{Invisible:1b},nbt={}]"
```
Comment (LMLiam) [inline modules/core/src/test/kotlin/io/github/lmliam/kotventure/core/selector/EntitySelectorTest.kt:355]: The behavior tests cover `entities`, `self`, and a negated call, but the acceptance contract also requires every selector head and no selector-level raw-string overload. Add one compile-success fixture spanning all six heads and one compile-fail fixture for `entities { nbt("{Health:20f}") }`.

File: modules/core/src/main/kotlin/io/github/lmliam/kotventure/core/selector/CommonEntitySelectorScope.kt (hunk 1 above)
Comment (LMLiam) [reply modules/core/src/main/kotlin/io/github/lmliam/kotventure/core/selector/CommonEntitySelectorScope.kt:154]: Addressed in cd8cc91. The public KDoc now explicitly rejects raw SNBT and directs raw-selector interop to `entitySelector(...)`.

File: modules/core/src/main/kotlin/io/github/lmliam/kotventure/core/selector/SelectorNbtFilter.kt (hunk 2 above)
Comment (LMLiam) [reply modules/core/src/main/kotlin/io/github/lmliam/kotventure/core/selector/SelectorNbtFilter.kt]: Addressed in cd8cc91. Renamed the string field to `renderedCompound`, making its serialized representation explicit.

File: modules/core/src/test/kotlin/io/github/lmliam/kotventure/core/selector/EntitySelectorTest.kt (hunk 3 above)
Comment (LMLiam) [reply modules/core/src/test/kotlin/io/github/lmliam/kotventure/core/selector/EntitySelectorTest.kt:355]: Addressed in cd8cc91. Added all-six-head compile coverage, negated-scope coverage, and a compile-fail fixture proving no selector `nbt(String)` overload exists.
